SumoLogic/sumologic-kubernetes-tools

README.md, src/k8s/tools-pod.yaml
Update documentation to use `values.yaml` as recommended way of generating templates
=> Add docs for custom values.yaml

deploy/docker/Dockerfile, src/commands/fix-log-symlinks
We want to add this bash script to the kubernetes tools so that we can recreate any log symlinks that kubernetes has deleted. This is based on a known open issue as referenced in the comment in-code
The idea would be to deploy this as a cronjob to run every few minutes. Please let me know if the below change looks reasonable :) 
I've verified that the script itself seems to work fine - I built it in a separate docker image and deployed on a test cluster.
But I'm new to developing for kubernetes tools - how can I build and test this? Once I run `ci/build.sh` to build the docker image, what are the next steps for testing? Thanks team!
=> log symlink checker

src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/router.rs, src/rust/receiver-mock/src/statistics.rs
This PR adds `--print-headers` to print incoming request's headers in the following format:
```
--> POST / HTTP/1.1
--> host: localhost:3000
--> user-agent: Telegraf/unknown Go/1.15
--> content-length: 212
--> content-encoding: gzip
--> content-type: application/vnd.sumologic.carbon2
--> accept-encoding: gzip
```
=> [receiver-mock] Add --print-headers flag

src/rust/receiver-mock/.rustfmt.toml, src/rust/receiver-mock/Makefile, src/rust/receiver-mock/src/main.rs
That's an example of a check that could run on CircleCI (to get quick feedback)
=> [receiver-mock] Add rustfmt config and make targets

deploy/docker/Dockerfile
Adding `-w` to `-ldflags` and bumping go toolchain version decreases resulting binaries sizes:
* `stress-tester` - from `8.2M` to `6.0M`
* `k8s-api-test` - from `29.4M` to `22.9M`
=> Update go builder image to use 1.15.2 and go build flags

.travis.yml
This also removes `branches` section as it's marked as deprecated as per https://config.travis-ci.com/ref/job/branches
> Branches
> Include or exclude branches from being built
> 
> Include or exclude branches for your build to be run on.
> 
> This is a **legacy** setting, use the more powerful condition (if) to define branches for your build to be run on.
> 
>
=> Run shellcheck and tests only for PRs

Dockerfile, ci/build.sh, src/commands/upgrade-2.0
This script outputs migrated values file on stdout (and saves it in new_values.yaml in current working directory).
Log produced by the migration script are available on stderr.
It takes values file as input either from stdin or as first (and only) script argument (with priority for the latter).
=> Add 2.0 migration script wrapper - upgrade-2.0 to Docker image

.github/workflows/dev_builds.yml, .github/workflows/pre_release_builds.yml, .github/workflows/release_builds.yml, Makefile
Fixes: https://github.com/SumoLogic/sumologic-kubernetes-tools/issues/161
I left publishing to Dockerhub in as the default for now. I also tested this in GHA, it successfully published `public.ecr.aws/a4t4y2n3/kubernetes-tools:2.5.0-24-g74a70ad`.
=> ci: publish images to ECR

.github/workflows/build_and_push_image.yml, .github/workflows/dev_builds.yml, .github/workflows/pre_release_builds.yml, .github/workflows/release_builds.yml, Makefile
Clean up the CI logic and workflows:
* always use cache when building images
* only push cache to registries in the dev workflow
* add a reusable workflow for building and pushing images, use it in other workflows to keep things DRY
The reusable workflow requires moving tag computation to a separate job, whose output is then used as an input to the build/push job. This is simply how reusable workflows work in GHA. There's a question of whether the reference to the reusable workflow should be pinned to a specific revision rather than following main, but since we control this, I think it's fine the way it is, and much easier to manage.
Should the dev workflow really be run on `release-v[0-9]+.[0-9]+`, by the way? Do we use release branches in this repo?
=> ci: clean up workflows

.github/workflows/build_and_push_image.yml, Makefile, docker-bake.hcl
More specifically, this is for ARMv8 support, though we can technically build for any platform supported by QEMU, rust, and go.
Use docker buildx for building the images, and organize the build targets in a `docker-bake.hcl` file for `docker buildx bake`. This allowed the Makefile to become simpler while encapsulating all the Docker-specific bits in a separate file. buildx also had superior build cache management, which unfotunately doesn't work on ECR yet, so for the time being we use Dockerhub exclusively for cache.
In the CI workflow, I switched from the "build once and push to multiple destinations" flow to "build and push to each destination in a single command". Build cache means we only build images once either way, and the latter fits the semantics of buildx better.
See successful …
=> Build multiplatform docker images

.github/CODEOWNERS
Similar to what we do in other repos:
- https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v2.2.0/.github/CODEOWNERS
- https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/v1.12.2-sumo-9/.github/CODEOWNERS
- https://github.com/SumoLogic/sumologic-kubernetes-setup/blob/afce3bb5a85b8d67a02bbb069bfb5c09b68aee2c/.github/CODEOWNERS
=> ci(codeowners): use team name only

src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/src/router.rs
Mostly simplify tests code, replace `test::load_stream(resp.take_body().into_stream())` into `test::read_body(resp)` (and remove unneeded now `futures-util`) and indent multiline strings.
=> refactor(receiver-mock): refactor tests

src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/src/metrics.rs, src/rust/receiver-mock/src/router.rs
Using serde with features instead of serde_derive as described in
https://serde.rs/derive.html.
=> chore(receiver-mock): bump dependencies via cargo update and some Cargo.toml cleanup

src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/README.md, src/rust/receiver-mock/src/logs.rs, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/metrics.rs, src/rust/receiver-mock/src/options.rs, src/rust/receiver-mock/src/router.rs, src/rust/receiver-mock/src/time.rs
We count logs by timestamp in a BTreeMap and expose the number via a `/logs/count` endpoint. It is assumed at the moment that the log body is a json object and that the timestamp is contained in the `timestamp` key.
The plan is to store metadata and allow filtering by it as well in the very near future.
=> Add log counting by timestamp range to receiver-mock

src/rust/receiver-mock/README.md, src/rust/receiver-mock/src/logs.rs, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/metadata.rs, src/rust/receiver-mock/src/router.rs
Store metadata for incoming logs based on the X-Sumo-Fields header value. Allow querying log counts based on using the same interface we have for metrics.
=> Filter logs by metadata in receiver-mock

src/rust/receiver-mock/src/logs.rs, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/metadata.rs, src/rust/receiver-mock/src/metrics.rs, src/rust/receiver-mock/src/router/mod.rs
We only got metadata from X-Sumo-Fields, this commit adds X-Sumo-Name, X-Sumo-Host and X-Sumo-Category. This covers all the headers supported by Sumo's HTTP sources.
=> feat(receiver-mock): get metadata from X-Sumo-* headers

Dockerfile
We're building Docker images for multiple platforms, but external tools like helm or kubectl were hardcoded for linux/amd64. This is now fixed.
=> fix: use tool binaries for the right platform

src/rust/receiver-mock/src/logs.rs, src/rust/receiver-mock/src/router/mod.rs
[`IntoIter`](https://doc.rust-lang.org/std/array/struct.IntoIter.html#method.new) got deprecated in rust 1.59 so migrate away from it and use [`std::iter::IntoIterator::into_iter`](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html#tymethod.into_iter) instead.
=> chore(receiver-mock): migrate from deprecated IntoIter

src/rust/receiver-mock/Cargo.toml
https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html#migrating-to-2021
=> chore(receiver-mock): bump rust edition to 2021

src/commands/pvc-cleaner
Current `kubectl describe pvc` output:
```
kubectl -n collection describe pvc file-storage-collection-sumologic-otelcol-logs-9
...
Used By:       collection-sumologic-otelcol-logs-9
```
Old `kubectl describe pvc` output:
```
kubectl -n collection describe pvc file-storage-collection-sumologic-otelcol-logs-9
...
Mounted By:       collection-sumologic-otelcol-logs-9
```
=> fix: kubectl pvc describe command changed and uses 'Used By' instead of 'Mounted By' now

src/rust/receiver-mock/README.md, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/router/mod.rs
add endpoint which just dumps requests (to test e.g. collectd plugin)
=> feat(receiver-mock): add dump endpoint

Dockerfile, src/rust/receiver-mock/.cargo/config.toml
After some investigation and tries, it comes out that the issue is result of using cargo buil-in git command along with Qemu:
See https://users.rust-lang.org/t/cargo-uses-too-much-memory-being-run-in-qemu/76531
for reference
=> chore(github actions): fix ci by using external git command

.github/workflows/pull_requests.yml, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/Makefile, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/router/api.rs, src/rust/receiver-mock/src/router/mod.rs
This PR updates `rustfmt` edition used in `Makefile` to 2021 (since the project is also set to that edition), formats the code using this updated `make` rule and adds a formatting check to the workflows.
=> chore: update formatting options

Dockerfile
After adding a support for otlp logs in the receiver mock, some checks did not pass because one of the newly added dependencies needed cmake to build ([ref](https://github.com/SumoLogic/sumologic-kubernetes-tools/actions/runs/2790052818)) and the build failed on the Docker image.
=> feat(Dockerfile): install cmake on the build image

src/rust/receiver-mock/src/main.rs
The tests use a path with this prefix for data in otlp format.
=> fix(receiver-mock): add "receiver" prefix to the otlp path

.github/workflows/pull_requests.yml
The workflow will now fail on any warning in compile time.
=> feat: add checking warnings to the workflow

src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/src/logs/mod.rs, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/metrics/mod.rs, src/rust/receiver-mock/src/router/mod.rs, src/rust/receiver-mock/src/router/otlp.rs
Resolves #34 
Printing with println and eprintln macros has been replaced with calls to macros from the `log` crate. A `simple_logger` has been used to log.
Please note that this change also causes dependencies to print logs (see the example output below). Due to that, please check if the log levels I assigned to each message are ok.
Technically, all logging calls can be replaced in the future with macros from the `tracing` crate, since they have the same API. I don't think that tracing would be particularly useful in this mock though.
Example output:
```
2022-08-24T11:15:39.236Z INFO [receiver_mock] Receiver mock is waiting for enemy on 0.0.0.0:3000!
2022-08-24T11:15:39.238Z INFO [actix_server::builder] Starting 8 workers
2022-08-24T11:15:39.238Z INFO [actix_server::server] Actix runtime …
```
=> feat(receiver-mock): change printing to logging

src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/router/mod.rs, src/rust/receiver-mock/src/router/otlp.rs
A simple handler that counts received spans has been added.
=> feat(receiver-mock): add handler for otlp traces

src/rust/receiver-mock/README.md, src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/router/otlp.rs, src/rust/receiver-mock/src/router/traces_data.rs, src/rust/receiver-mock/src/traces/mod.rs
Up to now, only querying single spans was possible. This PR adds possibility to query a whole trace - represented as a list of all its spans.
=> feat(receiver-mock): add querying whole traces

src/go/.gitignore, src/go/cmd/update-collection-v3/.gitignore
The previous version caused any files added in e.g. customer-trace-tester directory to be ignored.
=> chore: fix .gitignore

.github/workflows/pull_requests.yml, Dockerfile
The CI in #329 did not work, because `tonic` (used to build `opentelemetry-proto`) no longer introduces `protoc` binary. This PR adds installation steps of `protoc` to our workflows.
The installation step was taken from here: https://github.com/marketplace/actions/setup-protoc
A related issue in the upstream: https://github.com/open-telemetry/opentelemetry-rust/issues/873
=> ci: install protoc during workflow and while building image

.github/workflows/pull_requests.yml, Dockerfile, src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml
Upstream has finally released a crate for `opentelemetry-proto`, so we can fix the version used and change the source for it to crates.io, instead of github.
=> chore(receiver-mock): change the source of opentelemetry-proto to crates.io

src/go/cmd/update-collection-v3/main.go, src/go/cmd/update-collection-v3/migrations/tracing-replaces/migrate.go, src/go/cmd/update-collection-v3/migrations/tracing-replaces/values2.go, src/go/cmd/update-collection-v3/testdata/tracing-replaces.input.yaml, src/go/cmd/update-collection-v3/testdata/tracing-replaces.output.yaml
feat(update-collection-v3): add warning for special values with 'replace' suffix in configuration for otelcol and otelagent
related to https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2615
User will see following warning when special values with replace suffix are available in the configuration for otelcol and otelagent:
```
./update-collection-v3 --in values.input.yaml
WARNING! Found following special values in otelagent configuration which must be manually migrated:
- exporters.otlpmetrics.endpoint.replace
- exporters.otlptraces.endpoint.replace
for details please see documentation: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/docs/v3_migration_doc.md
WARNING! Found following special values in otelcol configuration which must be manually …
```
=> feat(update-collection-v3): add warning for special values with 'replace' suffix in configuration

src/go/cmd/update-collection-v3/main.go, src/go/cmd/update-collection-v3/migrations/events-config-merge/migrate.go, src/go/cmd/update-collection-v3/migrations/events-config-merge/testdata/basic.input.yaml, src/go/cmd/update-collection-v3/migrations/events-config-merge/testdata/basic.output.yaml, src/go/cmd/update-collection-v3/testdata/simple.input.yaml, src/go/cmd/update-collection-v3/testdata/simple.output.yaml
Migration for https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2643
=> feat(update-collection-v3): migrate otelevents.config.override

src/go/cmd/update-collection-v3/main.go, src/go/cmd/update-collection-v3/migrations/fluentd-autoscaling/common.go, src/go/cmd/update-collection-v3/migrations/fluentd-autoscaling/migrate.go, src/go/cmd/update-collection-v3/migrations/fluentd-autoscaling/migrate_test.go, src/go/cmd/update-collection-v3/migrations/fluentd-autoscaling/values_input.go, src/go/cmd/update-collection-v3/migrations/fluentd-autoscaling/values_output.go, src/go/cmd/update-collection-v3/migrations/fluentd-logs-configs/fluentd.go, src/go/cmd/update-collection-v3/migrations/fluentd-logs-configs/testdata/fluent-and-sumologic-without-logs.input.yaml, src/go/cmd/update-collection-v3/migrations/fluentd-logs-configs/testdata/fluent-and-sumologic-without-logs.output.yaml, src/go/cmd/update-collection-v3/testdata/simple.input.yaml, src/go/cmd/update-collection-v3/testdata/simple.output.yaml
This is a quality of life migration. If the user enabled autoscaling for FluentD, they presumably want it as well for otel. Otherwise we'd instead need to have users take manual steps to enable this, which is less convenient and makes the migration document longer and more complex.
I also fixed a small issue around handling empty structs in a different migration.
=> feat(update-collection-v3): add migration for FluentD autoscaling

src/go/cmd/update-collection-v3/main.go, src/go/cmd/update-collection-v3/migrations/logformat/migrate.go, src/go/cmd/update-collection-v3/migrations/logformat/migrate_test.go, src/go/cmd/update-collection-v3/migrations/logformat/values.go, src/go/cmd/update-collection-v3/testdata/simple.input.yaml, src/go/cmd/update-collection-v3/testdata/simple.output.yaml
Move `fluentd.logs.output.logFormat` to `sumologic.logs.container.format`. This migration tracks https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2794.
=> feat(update-collection-v3): add migration for log format

src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/src/router/api.rs
Made the necessary changes for #414 to succeed.
=> chore(receiver-mock): bump base64 to 0.21.0

src/go/cmd/update-collection-v3/README.md, src/go/cmd/update-collection-v3/main.go, src/go/cmd/update-collection-v3/testdata/containerd-multiline.input.yaml, src/go/cmd/update-collection-v3/testdata/containerd-multiline.output.yaml, src/go/cmd/update-collection-v3/testdata/multiline.input.yaml, src/go/cmd/update-collection-v3/testdata/multiline.output.yaml
=> fix(update-collection-v3): fix multiline property rendering

src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/src/main.rs
After https://github.com/SumoLogic/sumologic-kubernetes-tools/pull/349, the boolean flags on the command parser were effectively always set and impossible to disable. I've refactored the parser to use Derive and macros instead, which fixes that problem.
=> fix(receiver-mock): refactor command parser

src/go/cmd/update-collection-v3/migrations/kube-prometheus-stack-repository/testdata/all_values.input.yaml, src/go/cmd/update-collection-v3/migrations/kube-prometheus-stack-repository/testdata/all_values.output.yaml
https://kubernetes.io/blog/2023/03/10/image-registry-redirect/
=> chore: change k8s.gcr.io registry to registry.k8s.io

.github/workflows/dev_builds.yml, .github/workflows/pre_release_builds.yml, .github/workflows/release_builds.yml
remove _set-output_ based on https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Fix deprecations in github actions

src/rust/receiver-mock/src/main.rs, src/rust/receiver-mock/src/router/api.rs
This PR contains the following changes:
- add short flag `a` to `drop-rate`, because of build errors
- add `/otCollectors/metadata` endpoint
- add `/collector/{logs,metrics,traces}` endpoint referring to `router::otlp`
- rename `CollectorRegisterRespone` serialization keys
- add support for `Bearer ` authorization
I'm considering the following changes:
- rename `CollectorRegisterRespone` properties instead of renaming it during serialization
- drop support for `Basic ` authorization
=> feat(receiver-mock): update /api/v1 to match the latest otelcol version

.github/workflows/pull_requests.yml, src/go/cmd/update-collection-v3/helpers/helpers.go, src/go/cmd/update-collection-v3/helpers/helpers_test.go, src/go/cmd/update-collection-v3/migrations/disable-thanos/migrate.go, src/go/cmd/update-collection-v3/migrations/events-config-merge/migrate.go, src/go/cmd/update-collection-v3/migrations/events/migrate.go, src/go/cmd/update-collection-v3/migrations/falco-upgrade/migrate.go, src/go/cmd/update-collection-v3/migrations/fluentd-autoscaling/migrate.go, src/go/cmd/update-collection-v3/migrations/fluentd-logs-configs/migrate.go, src/go/cmd/update-collection-v3/migrations/kube-prometheus-stack-repository/migrate.go, src/go/cmd/update-collection-v3/migrations/kube-state-metrics-collectors/migrate.go, src/go/cmd/update-collection-v3/migrations/logformat/migrate.go, src/go/cmd/update-collection-v3/migrations/logs-metadata-config/migrate.go, src/go/cmd/update-collection-v3/migrations/metrics-metadata-config/migrate.go, src/go/cmd/update-collection-v3/migrations/otellogs-config-merge/migrate.go, src/go/cmd/update-collection-v3/migrations/remove-load-config-file/migrate.go, src/go/cmd/update-collection-v3/migrations/tracing-config/migrate.go, src/go/cmd/update-collection-v3/migrations/tracing-replaces/migrate.go, src/go/go.mod
This PR resolves the following case:
`inputStruct`
```
type in struct {
Rest           map[string]interface{} `yaml:",inline,omitempty"`
}
```
`values.yaml`
```
out: test
```
`outputStruct`
```
type out struct {
Out            string                 `yaml:"out,omitempty"`
Rest           map[string]interface{} `yaml:",inline,omitempty"`
}
```
`out` is in both `Rest` and Out` properties of `out` structure which leads to panic:
e.g.
`input.yaml`
```
otelcolInstrumentation:
enabled: false
```
`stdout`:
```
panic: cannot have key "otelcolInstrumentation" in inlined map: conflicts with struct field [recovered]
panic: cannot have key "otelcolInstrumentation" in inlined map: conflicts with struct field
goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc000133788) …
```
=> feat(update-collection-v3): check for conflicts between input and output yamls in migrations

src/rust/receiver-mock/src/main.rs
#462 accidentally removed the `--store-logs` option for receiver-mock. This change brings it back.
=> fix(receiver-mock): restore --store-logs option

src/rust/receiver-mock/Cargo.lock, src/rust/receiver-mock/Cargo.toml, src/rust/receiver-mock/src/router/otlp.rs
Update opentelemetry proto to 1.0.0. This supersedes #459 . I've also moved our Prometheus parsing package to a stable version - previously it was pinned to a commit.
=> feat(receiver-mock): update otel proto to 1.0.0

Makefile
Invalid env variable (`IMAGE`) has been used for Sumo Logic Mock image
=> chore: fix repo name for docker image build

src/rust/sumologic-mock/Cargo.lock, src/rust/sumologic-mock/Cargo.toml, src/rust/sumologic-mock/src/main.rs, src/rust/sumologic-mock/src/router/otlp.rs
Bump opentelemetry-proto to 0.5.0, prost to 0.12.3, and update all the other dependencies.
=> deps(sumologic-mock): update dependencies

.github/workflows/dev_builds.yml, .github/workflows/pre_release_builds.yml, .github/workflows/release_builds.yml
=> chore: fix dockerhub secret names in builds

src/rust/sumologic-mock/Cargo.lock, src/rust/sumologic-mock/Cargo.toml, src/rust/sumologic-mock/src/router/otlp.rs
Supersedes #720, needed minor code changes.
=> deps(sumologic-mock): bump opentelemetry-proto to 0.6.0

.github/workflows/dev_builds.yml, .github/workflows/pre_release_builds.yml, .github/workflows/release_builds.yml, Dockerfile.kubectl-ubi, Makefile, docker-bake.hcl
```
preflight check container docker.io/sumologic/kubernetes-tools-kubectl:2.22.0-122-g169e321-ubi
time="2024-05-27T11:50:38+02:00" level=info msg="certification library version" version="0.0.0 <commit: 354d10d9af8b5a64c7c2230a6656186957c3ed9f>"
time="2024-05-27T11:50:40+02:00" level=info msg="running checks for docker.io/sumologic/kubernetes-tools-kubectl:2.22.0-122-g169e321-ubi for platform amd64"
time="2024-05-27T11:50:40+02:00" level=info msg="target image" image="docker.io/sumologic/kubernetes-tools-kubectl:2.22.0-122-g169e321-ubi"
time="2024-05-27T11:50:51+02:00" level=info msg="check completed" check=HasLicense result=PASSED
time="2024-05-27T11:50:51+02:00" level=info msg="check completed" check=HasUniqueTag result=PASSED
time="2024-05-27T11:50:51+02:00" level=info msg="check …
```
=> feat: build kubectl UBI based image 

Dockerfile.kubectl
Update the base image to `5.2.26-alpine3.20`. Not sure why dependabot doesn't do this, maybe the version has the wrong format?
Also update kubectl to the latest patch version in the 1.27 line.
This addresses the following CVEs:
- https://www.cve.org/CVERecord?id=CVE-2023-5363
- https://www.cve.org/CVERecord?id=CVE-2023-44487
- https://www.cve.org/CVERecord?id=CVE-2023-45288
=> deps(kubectl): update dependencies
