SumoLogic/sumologic-kubernetes-tools

README.md
deploy/docker/Dockerfile
src/commands/template
src/commands/tools-usage

Add templating as requested in #4

Add templating functionality and do some visual fixes

---

ci/build.sh

https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth

Set Travis build with unshallow git clone

---

README.md
src/commands/tools-usage

Remove generator flag

---

README.md

Add requirement of kubectl 1.14 for the template generator

---

src/commands/template

Filter out crd-install hook warning

---

README.md
src/commands/template

Fixes #13 
I didn't reproduced the issue from #13, but as we changed the design, the issue should be solved anyway

Simplify template generation

---

src/rust/receiver-mock/src/metrics.rs
src/rust/receiver-mock/src/router.rs

As described in https://help.sumologic.com/Metrics/Introduction-to-Metrics/Metric-Formats#graphite

[receiver-mock] Support graphite metrics

---

.dockerignore
deploy/docker/Dockerfile

```
docker image inspect --format "{{ .Size }}" sumologic/kubernetes-tools:local
128917914
```
-> 
```
docker image inspect --format "{{ .Size }}" sumologic/kubernetes-tools:local
123232068
```

Refactor Dockerfile

---

src/rust/receiver-mock/src/router.rs

It seems we didn't clear the metrics count so this PR addresses that + it adds a handful of tests for that.

[receiver-mock] Fix metrics-reset handler

---

README.md
ci/build.sh
deploy/docker/Dockerfile
src/commands/template
src/commands/template-dependency
src/commands/template-prometheus-mixin/jsonnet-mixin.tmpl
src/commands/template-prometheus-mixin/template-prometheus-mixin

Add template-prometheus-mixin command

---

deploy/docker/Dockerfile

Add `kubectl` v1.18.10 binary to the image.

Add kubectl to the image

---

src/commands/template

Fix: /usr/bin/template: line 24: [: -t: binary operator expected

Fix template generation

---

src/commands/template

[template] Do not skip line read by read

---

README.md

docs: add info about container registries and available architectures

---

README.md

docs(readme): fix ECR repo name

---

src/commands/fix-log-symlinks

fix(fix-symlink): use ls instead of *

---

src/go/cmd/update-collection-v3/main.go
src/go/cmd/update-collection-v3/migrate.go
src/go/cmd/update-collection-v3/valuesv3.go

Prepare separate structure for v2 and v3 and copy all values by default

feat(update-collection-v3): copy all values by default

---

src/rust/receiver-mock/Cargo.lock
src/rust/receiver-mock/Cargo.toml
src/rust/receiver-mock/src/main.rs
src/rust/receiver-mock/src/router/mod.rs
src/rust/receiver-mock/src/router/otlp.rs

feat(receiver-mock): add support for otlp logs

---

src/rust/receiver-mock/src/router/mod.rs
src/rust/receiver-mock/src/router/otlp.rs

Ref: https://github.com/SumoLogic/sumologic-kubernetes-tools/pull/294#pullrequestreview-1069501042
This PR refactors the code by extracting some functions that are used by different receivers.

refactor(receiver-mock): extract common functions for receivers

---

src/go/cmd/update-collection-v3/main_test.go
src/go/cmd/update-collection-v3/migrate.go
src/go/cmd/update-collection-v3/migrate_test.go
src/go/cmd/update-collection-v3/valuesv2.go
src/go/cmd/update-collection-v3/valuesv3.go

feat(update-collection-v3): add kube-state-metrics migration

---

src/go/cmd/update-collection-v3/events.go
src/go/cmd/update-collection-v3/events_test.go
src/go/cmd/update-collection-v3/main.go
src/go/cmd/update-collection-v3/migrate.go
src/go/cmd/update-collection-v3/valuesv2.go
src/go/cmd/update-collection-v3/valuesv3.go

This includes #304, should be merged afterwards.

Add event config migration for v3

---

src/rust/receiver-mock/Cargo.lock
src/rust/receiver-mock/Cargo.toml
src/rust/receiver-mock/src/main.rs
src/rust/receiver-mock/src/metrics.rs
src/rust/receiver-mock/src/router/otlp.rs

feature(receiver-mock): add support for otlp metrics

---

src/rust/receiver-mock/src/router/mod.rs
src/rust/receiver-mock/src/router/otlp.rs

Fixes #295 
This PR removes unwraps related to user input and sends Bad Request instead.

fix(receiver-mock): don't panic while handling requests

---

Dockerfile
src/rust/receiver-mock/Cargo.lock
src/rust/receiver-mock/Cargo.toml
src/rust/receiver-mock/src/main.rs

chore(receiver-mock): upgrade clap to the newest version

---

src/rust/receiver-mock/src/logs/mod.rs

Follow-up to #381 
The regexes are now being cached. 
Sadly, benchmarks in Rust are unstable, but I can try making some if needed.

feat(receiver-mock): add caching regexes

---

src/go/cmd/update-collection-v3/main.go
src/go/cmd/update-collection-v3/migrations/otellogs-config-merge/migrate.go
src/go/cmd/update-collection-v3/migrations/otellogs-config-merge/testdata/basic.input.yaml
src/go/cmd/update-collection-v3/migrations/otellogs-config-merge/testdata/basic.output.yaml
src/go/cmd/update-collection-v3/testdata/simple.input.yaml
src/go/cmd/update-collection-v3/testdata/simple.output.yaml

Migration for https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2652. Basically identical to #389.

feat(update-collection-v3): migrate otellogs.config.override

---

src/go/cmd/update-collection-v3/main.go
src/go/cmd/update-collection-v3/migrations/metrics-server-upgrade/migrate.go
src/go/cmd/update-collection-v3/migrations/metrics-server-upgrade/migrate_test.go

feat(upgrade_to_v3): add migration warnings for metrics-server changes

---

src/go/cmd/update-collection-v3/main.go
src/go/cmd/update-collection-v3/migrations/tailing-sidecar-operator-upgrade/migrate.go
src/go/cmd/update-collection-v3/migrations/tailing-sidecar-operator-upgrade/migrate_test.go

feat(upgrade_to_v3): add migration warnings for tailing-sidecar-operator

---

src/go/cmd/update-collection-v3/migrations/fluentd-logs-configs/fluentd.go
src/go/cmd/update-collection-v3/migrations/fluentd-logs-configs/testdata/fluent-config-additional-logs-config.input.yaml
src/go/cmd/update-collection-v3/migrations/fluentd-logs-configs/testdata/fluent-config-additional-logs-config.output.yaml

fix(update-collection-v3): fix migration of configuration with missing sumologic key
and additional configuration under fluentd.logs key

fix(update-collection-v3): fix migration of configuration 

---

.github/workflows/build_binaries.yml
.github/workflows/dev_builds.yml
.github/workflows/release_builds.yml
src/go/cmd/update-collection-v3/Makefile

Building helm chart v3 migration tool binaries
Binaries from a test run can be found below:
https://github.com/SumoLogic/sumologic-kubernetes-tools/actions/runs/3941261582

Building helm chart v3 migration tool binaries

---

.github/workflows/release_builds.yml

The release action didn't have artifacts uploaded. Also fixed the version tag.

ci: fix release action

---

Makefile
docs/release.md

Added release doc and makefile targets to create, push and delete a tag

Added release doc and makefile targets to create, push and delete a tag

---

src/go/cmd/update-collection-v3/main.go
src/go/cmd/update-collection-v3/main_test.go

The test will currently fail, as the fix is in #446. Once that lands, I'll rebase. Right now it shows that the test actually works.

fix(update-collection-v3): check migration directories in tests

---

src/go/cmd/update-collection-v3/migrations/tracing-config/migrate.go
src/go/cmd/update-collection-v3/migrations/tracing-config/values_input.go
src/go/cmd/update-collection-v3/migrations/tracing-config/values_output.go
src/go/cmd/update-collection-v3/testdata/tracing.input.yaml
src/go/cmd/update-collection-v3/testdata/tracing.output.yaml

PR improves migration, thanks to that customer will not need to tune up again his instrumentation pipeline.
PR fixes: https://github.com/SumoLogic/sumologic-kubernetes-tools/issues/445

feat(tracing): improve migration

---

.github/workflows/build_binaries.yml

chore(deps): update go to 1.21

---

.github/workflows/dev_builds.yml
Dockerfile.sumologic-mock
Makefile

Example run for main branch: https://github.com/sumo-drosiek/sumologic-kubernetes-tools/actions/runs/7626673639/job/20773600581
Example run for release: https://github.com/sumo-drosiek/sumologic-kubernetes-tools/actions/runs/7626719925/job/20773756948

fix: fix builds for Sumo Logic Mock

---

src/rust/sumologic-mock/src/router/mod.rs

Empty data is being treated as plaintext log.

feat(sumologic-mock): accept empty Content-Type header for incoming data
